### ISSUE TITLE
can not find semgrep installed by pip in WSL

### ISSUE THREAD

**Issue by tuhaolam** [returntocorp/semgrep-vscode#15] opened 2021-05-19 06:58 UTC
![image](https://user-images.githubusercontent.com/10894348/118769235-8893a900-b8b2-11eb-962a-564da34eb3de.png)

```
Semgrep is not installed, try running `pip install semgrep`. Linting will be disabled until restart.
```

**Comment by Spencer-Dawson** [comment] 2021-07-21 21:16
95% certain this is a Duplicate of #12 
I'm seeing this as well.

**Comment by ajbt200128** [comment] 2022-07-28 16:52
See closing comment of #12! Feel free to re-open if that isn't a solution

**Closed by ajbt200128** 2022-07-28 16:52 UTC
