### ISSUE TITLE
VS Code cannot find Semgrep path

### ISSUE THREAD

**Issue by chmccreery** [returntocorp/semgrep-vscode#12] opened 2021-03-12 18:52 UTC
Several users have now told us that they have Semgrep installed, and can run it from inside their VS Code terminal, but the extension is not picking it up. It may be a pip/pip3 issue (at least that seems to have resolved it for one person). Most are using apple computers.

**Comment by dlukeomalley** [comment] 2021-03-23 18:47
@chmccreery Moving this to priority medium in relation to other issues we're tracking.

**Comment by iloveicedgreentea** [comment] 2021-03-24 19:23
I installed via brew on mac os and got the same error.

**Comment by chmccreery** [comment] 2021-03-25 03:31
@iloveicedgreentea the vs code extension doesn't support brew installs right now, only pip. Sorry about that!

**Comment by Spencer-Dawson** [comment] 2021-07-21 21:44
vscode is not finding my semgrep install either. 

I'm using vscode in windows using the Remote -WSL environment. 
In my case the ubuntu version I'm using for wsl2 is the default (20.04LTS).

Without reviewing this codebase thoroughly I suspect this extension is assuming semgrep is included in the user path and that is not the case for me with WSL2.
The default python for my wsl install seems to be 2.7 and of course semgrep is a python3 package.

I know semgrep is working if I execute it manually "python3 ~/.local/lib/python3.6/site-packages/semgrep"

So I don't think this issue just affects mac users. 

If my user path assumption is correct then I would suggest that you either document that in the install instructions or provide a workaround via some "semgrep.path" variable

**Comment by ajbt200128** [comment] 2022-06-28 22:55
Looks like this is partially a dupe of #3

**Comment by andig** [comment] 2022-07-11 15:19
> I installed via brew on mac os and got the same error.

Same problem here. Extension suggests to run the pip install, but it's already installed though homebrew.

**Comment by ajbt200128** [comment] 2022-07-28 16:49
We now support m1 macs through pip, and the extension will prompt you to install semgrep if it's not detected, and then automatically install it if you want it to

**Closed by ajbt200128** 2022-07-28 16:49 UTC
Labels: alpha, priority:low
